package com.bestsoft.litemall.db.dao;

import com.bestsoft.litemall.db.domain.LitemallBusiUser;
import com.bestsoft.litemall.db.domain.LitemallBusiUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LitemallBusiUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    long countByExample(LitemallBusiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallBusiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    int insert(LitemallBusiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    int insertSelective(LitemallBusiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    LitemallBusiUser selectOneByExample(LitemallBusiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    LitemallBusiUser selectOneByExampleSelective(@Param("example") LitemallBusiUserExample example, @Param("selective") LitemallBusiUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    List<LitemallBusiUser> selectByExampleSelective(@Param("example") LitemallBusiUserExample example, @Param("selective") LitemallBusiUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    List<LitemallBusiUser> selectByExample(LitemallBusiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    LitemallBusiUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallBusiUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    LitemallBusiUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    LitemallBusiUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallBusiUser record, @Param("example") LitemallBusiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallBusiUser record, @Param("example") LitemallBusiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallBusiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallBusiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallBusiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_busi_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}